### ISSUE TITLE
Apple ocsp server should not be blocked

### ISSUE THREAD

**Issue by jfb-pihole** [Ultimate-Hosts-Blacklist/MinimalHostsBlocker#1]
ocsp.apple.com is a valid domain for apple for certificate verification and should not be included on your block list

**Comment by funilrys** [comment]
@jfb-pihole Thanks for reporting. ping to @reddestdream as it is this list.

@jfb-pihole Can you fill a PR to  https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/master/domains.list so that it will be whitelisted tomorrow on the next update of https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist ?

Thanks in advance.

Have a nice day/night.

Cheers,
Nissar

**Comment by funilrys** [comment]
P.S: Please do not close this until the PR or a commit fixing this in the whitelist repository has been submitted.
